# Probability exercises

### Exercise 1 

Two unbiased dice are thrown once and the total score is observed. Use a simulation to find the estimated probability that the total score is even or greater than 7

We could use a mathematical equation to solve this or we can run the experiment many times, and then count the number of times where the score is even or greater than 7

-Run the experiment 1000 times (roll 2 dice 1000 times, and sum the result)

-Keep track of the number of times that the sum was either greater than 7 or an even number

-Divide the number from step 2 by the number of iterations (1000)


In [62]:
#import libraries
import numpy as np



#Funtion to roll the dice.
def rollDice(times = 1000):    
    accumulator = 0
    np.random.seed(24)
    for i in range(0,times):
        result = np.random.randint(1,7) + np.random.randint(1,7)
        if( result > 7 or result % 2 == 0):
            accumulator += 1
    return accumulator

print(f'Estimada probabilidad de premisa basado en 1000 intentos: {rollDice()/1000}')

Estimada probabilidad de premisa basado en 1000 intentos: 0.654


### Exercise 2

A box contains 10 white balls, 20 reds and 30 greens. Draw 5 balls with replacement. What is the probability that:

a. 3 white or 2 red

b. All 5 are the same color


We will use the same system here. We will pick our balls during each round and count the number of times that:

a. 3 white or 2 red 

b. All 5 are the same color.

In [68]:
#import libraries
import numpy as np
d = {}

for i in range(60):
    if i < 10:
        d[i] = 'White'
    elif i > 9 and i < 30:
        d[i] = 'Red'
    else:
        d[i] = 'Green'  
  
        
#Initialize important variables

n_simulations = 1000
lst = []
success_A = 0
success_B = 0
#np.random.seed(3)
for (k,v) in d.items():
    if( v == 'White'):
        lst.append(0)
    elif(v == 'Red'):
        lst.append(1)
    elif(v == 'Green'):
        lst.append(2)
lst = np.array(lst)
#print(lst)

for i in range(n_simulations):
    #make a list of the colors that we choose
    colors_chosen = np.array([lst[np.random.randint(0,60)],lst[np.random.randint(0,60)],lst[np.random.randint(0,60)],lst[np.random.randint(0,60)],lst[np.random.randint(0,60)]])
    print(colors_chosen)
    

    #Convert it to a numpy array
   

    #find the number of each taht we picked

    w = sum(colors_chosen == 0)
    r = sum(colors_chosen == 1)
    g = sum(colors_chosen == 2)
    # print(w,r,g)

    
    
    
    #Keep track if the combination met the criteria
    if( w == 3 and r == 2):
        success_A += 1
    if(w== 5 or r == 5 or g == 5):
        success_B += 1
    print(success_A,success_B)
    

#print 'the probability of 3 white and 2 red is' in percentage
print(f'Caso A (practica): {round(100*success_A/n_simulations,3)}%')
#print 'the probability of all the same color is' in percentage   
print(f'Caso B (practica): {round(100*success_B/n_simulations,3)}%')

[1 0 2 2 2]
0 0
[1 1 1 2 1]
0 0
[2 2 1 2 2]
0 0
[2 2 2 0 1]
0 0
[1 1 2 2 0]
0 0
[2 2 2 1 0]
0 0
[2 0 2 2 0]
0 0
[0 2 2 2 2]
0 0
[1 2 2 2 2]
0 0
[2 1 2 2 1]
0 0
[2 2 2 2 1]
0 0
[2 1 1 2 0]
0 0
[1 2 2 0 1]
0 0
[0 2 2 1 1]
0 0
[1 2 2 2 2]
0 0
[2 2 0 1 1]
0 0
[0 0 2 1 0]
0 0
[2 2 1 2 2]
0 0
[1 2 2 2 1]
0 0
[2 0 1 0 2]
0 0
[2 0 2 0 2]
0 0
[1 0 1 2 2]
0 0
[1 2 2 1 0]
0 0
[1 1 2 2 2]
0 0
[0 2 2 1 1]
0 0
[2 0 2 2 2]
0 0
[1 0 2 2 0]
0 0
[2 1 1 2 0]
0 0
[2 1 2 0 1]
0 0
[2 1 1 1 2]
0 0
[2 2 1 0 2]
0 0
[2 1 1 1 1]
0 0
[2 1 1 0 2]
0 0
[1 0 1 2 2]
0 0
[2 2 1 1 1]
0 0
[1 1 2 1 0]
0 0
[1 1 1 0 1]
0 0
[0 2 2 1 1]
0 0
[2 2 2 1 1]
0 0
[1 2 1 0 2]
0 0
[2 1 2 2 1]
0 0
[1 2 2 2 2]
0 0
[2 1 2 2 1]
0 0
[1 2 0 2 2]
0 0
[2 2 1 2 2]
0 0
[2 1 2 2 2]
0 0
[0 2 1 2 2]
0 0
[0 2 2 2 0]
0 0
[1 2 2 1 2]
0 0
[2 1 1 2 2]
0 0
[0 2 2 1 1]
0 0
[2 2 2 0 2]
0 0
[2 1 0 2 2]
0 0
[2 0 2 1 0]
0 0
[1 2 2 2 2]
0 0
[1 2 2 1 2]
0 0
[1 2 2 0 0]
0 0
[0 0 1 1 2]
0 0
[2 1 0 2 0]
0 0
[1 2 2 0 2]
0 0
[2 0 2 1 0]
0 0
[2 1 1 1 2]
0 0
[2 2 2 2